general:
  install:
    createTablespace: true
    deployIsvdi: true
    deployDb: true
    deployLdap: true
    deployIsvart: false
    externalSecret:
      extcreds: false
      isvdcerts: false
      isvdcred: false
      isvdicerts: false
      isvgimcerts: false
      metricscreds: false
      mqcerts: false
      mqcreds: false
      oidccreds: false
      pgcerts: false
      pgcreds: false
      regcred: false
db:
  user: postgres
  password:
  dbtype:
  ip:
  port:
  name: ivig
  admin: postgres
  adminPwd:
  isOracleServiceName: true
  security.protocol: ssl
  tablespace.location.data: /var/lib/postgresql/data/isvgimdata
  tablespace.location.indexes: /var/lib/postgresql/data/isvgimindexes
ldap:
  security.principal: cn=root
  security.credentials:
  defaulttenant.id: demo
  organization.name: Demo
  ldapserver.ip:
  ldapserver.port:
  ldapserver.root: dc=ivig
  security.protocol: ssl
mail:
  authentication.type: basic
  baseurl: https://foo.com/
  from: ivig@foo.com
  host: mailservice.mailpit.svc.cluster.local
  smtp.port: 1025
  smtp.starttls.enable: false
  smtp.auth: true
  smtp.auth.user: ivig
  smtp.auth.password:
office365:
  monitoring.enabled: false
  user.id:
  tenant.id:
  client.id:
  client.secret:
  scan.interval.minutes:
  graph.token.endpoint:
  graph.messages.endpoint:
  graph.user.agent:
server:
  options:
  - name: libertyMetrics
    enabled: true
    data:
    - name: userName
      value: null
    - name: password
      value: null
  flags:
    disableTLSv12: false
    enableFIPS: false
    secureSessionCookies: true
    globalHSTS: true
    hideServerVersion: false
  hostname:
  - k3s.mmfa.ibm.com
  - 192.168.42.245
  truststore:
  - '@isvgimRootCA.crt'
  - '@iviawrp.crt'
  keystore: null
oidc:
  isc:
  - scope=openid
  - discoveryEndpointUrl=https://www.iamlab.ibm.com/isvaop/oauth2/.well-known/openid-configuration
  - issuerIdentifier=https://www.iamlab.ibm.com
  - logoffUrl=https://www.iamlab.ibm.com/isvaop/oauth2/rplogout
  - audiences=isim
  - pkceCodeChallengeMethod=S256
  rest:
  - scope=openid
  - discoveryEndpointUrl=https://www.iamlab.ibm.com/isvaop/oauth2/.well-known/openid-configuration
  - issuerIdentifier=https://www.iamlab.ibm.com
  - logoffUrl=https://www.iamlab.ibm.com/isvaop/oauth2/rplogout
  - jwtAccessTokenRemoteValidation=require
  - validationMethod=introspect
  - inboundPropagation=supported
  - audiences=isim,isimrestapi
  - tokenReuse=true
  - accessTokenCacheTimeout=10s

