# structure intentionally compatible with values.yaml of starterkit

namespace: ivig-idm
timezone: Europe/Vienna
isOpenShift: false
fips: false
licenseType: PROCESSOR
clusterUrl: https://kubernetes.default.svc

images:
  isvgim: icr.io/isvg/identity-manager:11.0.2.0
  isvdi: icr.io/isvdi/verify-directory-integrator-dispatcher:11.0.0.1
  isvd: icr.io/isvd/verify-directory-server:11.0.1.0
  isvdproxy: icr.io/isvd/verify-directory-proxy:11.0.1.0
  isvdseed: icr.io/isvd/verify-directory-seed:11.0.1.0
  mq: icr.io/isvg/mq:10.0.0.0
  postgres: postgres:15.18-bookworm
  kuberbac: icr.io/isvg/kube-rbac-proxy:v0.16.0
  kubegres: icr.io/isvg/kubegres:1.19
  riskengine: icr.io/isvg/ivig-ae:11.0.2.0

storage:
  className: local-path
  mode: ReadWriteOnce
  volumes:
    isvd: 1Gi
    isvdproxy: 200Mi
    isvdi: 1Gi
    isvgimcustom: 500Mi
    mqlocal: 2Gi
    mqshare: 2Gi
    postgres: 1Gi
    riskengine: 10Gi

services:
  isvdi:
    ports:
      api: 1099
      object: 42001
  isvd:
    auditlog: false
    group: 1000
    ports:
      ldaps: 9636
    probes:
      initialDelaySeconds: 30
      periodSeconds: 10
    rootSuffix: dc=ivig
    user: 1000
    pgSharedMemory: 64Mi
  isvdproxy:
    auditlog: false
    group: 1000
    ports:
      ldapsproxy: 9636
      node: 30636
    probes:
      initialDelaySeconds: 30
      periodSeconds: 10
    user: 1000
  isvgim:
    config:
      adminUITimeoutSeconds: 1800
      iscUITimeoutSeconds: 1800
      healthcheckHeartbeatInSecs: 30
      debugInitScripts: false
      minReadySeconds: 5
      replicas: 1
      libertyConsoleLogLevel: AUDIT
      libertyLogMaxFileSize: 20
      libertyLogMaxFiles: 10
      libertyLtpaTimeout: 120
      libertyVerifyHostname: true
      libertyTrustLocalHosts: false
      libertyTransactionTimeout: 1200s
    ports:
      https: 9443
      iiop: 30809
      iiops: 30402
      node: 30943
      hazelcast: 5701
    probes:
      failureThreshold: 10
      initialDelaySeconds: 60
      periodSeconds: 15
      successThreshold: 1
      timeoutSeconds: 10
  mqlocal:
    group: 1001
    ports:
      mq: 1414
      console: 9444
    probes:
      failureThreshold: 3
      initialDelaySeconds: 30
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    qmgr: ISVGQueueMgr
    user: app
  mqshare:
    group: 1001
    hostname: mqshare
    ports:
      mq: 1414
      console: 9443
    probes:
      failureThreshold: 3
      initialDelaySeconds: 20
      periodSeconds: 10
      successThreshold: 1
      timeoutSeconds: 10
    qmgr: ISVGQMgrShared
    user: app
  postgres:
    group: 999
    dbName: ivig
    ports:
      pg: 5432
      node: 30543
    user: 999
    sharedMemory: 64Mi
  riskengine:
    serviceAccount: ivigrisk
    user: 1001

